name: Docker Build and Push
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: pip install mlflow==2.19.0 scikit-learn pandas dagshub

      - name: Train Model
        run: mlflow run MLProject --env-manager local

      - name: Build and Push Docker
        run: |
          RUN_ID=$(ls -t mlruns/0 | grep -v "meta.yaml" | head -n 1)
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          
          mlflow models build-docker \
            -m "mlruns/0/$RUN_ID/artifacts/model" \
            -n "${{ secrets.DOCKER_HUB_USERNAME }}/credit-scoring-project" \
            --enable-mlserver
          
          docker push "${{ secrets.DOCKER_HUB_USERNAME }}/credit-scoring-project:latest"